-- Lengthens 15 randomly-selected existing chapters (roughly doubling
-- each, while preserving the same characters/scene and any already-tagged
-- word) using the ElevenLabs credit remaining after the full-catalog
-- narration generation. audio_url_female/male are reset to NULL here so
-- scripts/generateNarration.js regenerates them for the new, longer text -
-- the old audio no longer matches. This batch intentionally regenerates
-- with a single voice (--voice=female), not both, to fit the remaining
-- credit; audio_url_male stays NULL afterward, so the voice toggle simply
-- won't show for these chapters (PlayerPage.jsx already handles a chapter
-- having only one gendered audio_url gracefully).

UPDATE chapters SET transcript = $$While looking into it, Elena noticed something worse buried nearby: passwords were being stored in a way that wasn't properly hashed, sitting there in plain text for anyone with database access to read. She flagged it immediately instead of quietly fixing it later, since a problem this serious deserved a paper trail. Then she fixed it properly: the system would now encrypt every password before it ever touched the database, using a well-tested library instead of anything homemade. She also wrote a short migration to re-hash every existing password the next time each user logged in, so the fix protected accounts that already existed, not just new ones going forward.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '3a06f00f-3762-4ad6-a087-0e13f3137beb';
UPDATE chapters SET transcript = $$Elena was reviewing a bug report that confused two very different failures, and the confusion itself was the real bug. Authentication checks who you are - did this password actually match this account, does this token belong to a real, still-valid session. Authorization checks something completely different: what you're allowed to do once you're already in. Just because you're logged in doesn't mean you're allowed to see everyone else's data, and just because a request carries a valid token doesn't mean every endpoint should trust it blindly. The report described a user who was authenticated just fine, but somehow reached another customer's invoices - the login worked exactly as designed, and the authorization check was simply missing.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = 'ad948fc1-4272-4487-a8a0-f3841b69117c';
UPDATE chapters SET transcript = $$Elena patched the vulnerability the same day it was reported, resisting the urge to wait for a "better" release window - a real vulnerability doesn't wait for anyone's convenience. She deployed the fix immediately, watched the monitoring dashboards for an hour afterward just to be sure nothing broke, and only then wrote back to the researcher, thanking them by name and explaining exactly what had been fixed. She also added a short note to the internal changelog, since two other teams used the same authentication library and deserved the same warning. Being fast and honest about a real problem built more trust with that researcher than pretending it never happened ever could have - he later said it was the fastest response he'd gotten from any company that year.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '8b009c21-c5d7-4461-8a09-686109279431';
UPDATE chapters SET transcript = $$Amara opened a pull request explaining exactly what she'd changed and why, linking back to the original issue so a reviewer wouldn't have to go looking for context on their own. She also added a short note about how she'd tested the fix locally, since she knew maintainers of a busy project couldn't always run every change themselves. It was her first pull request to a project she didn't own, and she reread the description three times before submitting it, half expecting someone to point out a mistake she'd missed. Once it was up, there was nothing left to do but wait - the strange, quiet part of contributing to open source that no tutorial ever really prepares you for.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '108fe4f5-6df8-4ad5-b3c4-821bcf5e01bf';
UPDATE chapters SET transcript = $$Ben worked in small steps, and after fixing the first bug in his login flow, he made a commit that described exactly what changed and why - not just "fix bug," but the actual reasoning behind the fix: a token was expiring one second earlier than the client expected, causing a rare but real race condition. He could have written a single vague line and moved on, but he'd been the person confused by someone else's vague commit message too many times to do that to a future teammate. Months later, when someone asked why that line existed, the commit message answered the question before anyone had to ask him directly, and nobody needed to track him down or guess at his intent from three years earlier. That, more than any comment in the code itself, was what actually explained the decision.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '58536993-4bf9-4c70-9d7a-e4e3f24f05bc';
UPDATE chapters SET transcript = $$Ana opened the full build log instead of just the summary. Scrolling past the setup steps, she found the exact line where things went wrong: a dependency install step had failed because of a version mismatch in a package she'd added that morning, one she hadn't even realized had a peer dependency on something the project already pinned to an older version.

It would have been easy to miss if she'd only glanced at the red X and assumed it was her test code. The actual failure was two steps earlier, in a part of the pipeline she hadn't even thought about - the exact kind of mistake that looks obvious in hindsight and invisible in the moment.

Reading the log carefully, instead of guessing, took less than two minutes and pointed her directly at the real problem. She pinned the dependency to a compatible version, pushed a tiny follow-up commit, and watched the build go green on the very next run.

She added a short comment next to the version pin explaining why it was there, so the next person who considered upgrading that package would find the answer immediately instead of rediscovering the same failure from scratch.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '21115023-911b-4c49-a4c0-48a1b332fac5';
UPDATE chapters SET transcript = $$Reading the code wasn't enough to see why the value went missing, so Omar added a breakpoint right before the payment function ran, exactly where the discount value was supposed to already exist. He triggered the same checkout again, this time in a staging environment built to match production closely rather than his own local setup, since the bug had never once reproduced there. When execution paused at the breakpoint, he inspected the real values instead of assuming what they'd be - a habit that had saved him more than once. The discount was arriving as an empty string instead of null, and one line of code, written months earlier by someone who'd since left the team, was checking only for null. It wasn't a dramatic bug, just a single overlooked case, but it had been silently breaking checkouts for a specific group of customers for weeks.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = 'd7a5ac43-348f-4c00-b351-558e7cfac167';
UPDATE chapters SET transcript = $$The fix itself was small - a missing space in a formatted string that made two words run together in the CLI's output - but Amara wrote a test to cover it anyway, so the same mistake couldn't quietly come back later after someone refactored that function without knowing why the space mattered. She ran the full test suite locally before touching anything else, just to be sure she hadn't broken something unrelated in a codebase she still barely knew her way around. It passed on the first try, which felt like a small victory in itself - proof that she'd actually understood the code well enough to change it safely, not just guessed at a fix that happened to look right.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = 'f08ec8e9-21aa-4e68-97c4-1da403c60fc9';
UPDATE chapters SET transcript = $$After some back and forth, the team committed to ten tickets for the sprint, deliberately leaving a little slack instead of packing the schedule completely full. Two people pushed to add an eleventh ticket that looked quick, but Mateo held the line, reminding everyone that "quick" tickets were exactly the ones that tended to hide a surprise. Mateo had learned that an optimistic sprint always felt worse at the end than a realistic one - not because less got done, but because the gap between what was promised and what shipped ate at everyone's confidence, sprint after sprint, in a way that was hard to undo.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '0b2c3e83-b623-4963-98be-60d112cb7ceb';
UPDATE chapters SET transcript = $$Chen scheduled a thirty-minute meeting instead of trying to settle it over chat. Decisions this size, she'd learned, needed a real conversation, not a thread that dragged on for two days with everyone talking past each other in separate replies.

She opened with the actual trade-off, not a recommendation - she wanted the room to reach the answer together, not just approve whatever she'd already decided. They went around one by one. The frontend lead didn't have a strong opinion either way, since the change was invisible from where he sat. The on-call engineer cared most about what would page him at 3 AM, and the queue clearly won there, since it meant one fewer service that could silently fail under load. The one holdout worried about the added operational complexity, and Chen didn't dismiss it - she let it sit on the table until he'd said his piece completely.

By the end of the meeting, they had reached consensus, not because everyone loved the idea equally, but because everyone understood why it mattered and had actually been heard.

Chen left the meeting relieved. A decision made with consensus was much easier to defend later than one made alone, and if it turned out to be wrong, it would be wrong as a team, which somehow made it easier to fix without anyone getting defensive about it.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = 'd0b8ede3-c152-4447-9bf9-91ecb4ae1f56';
UPDATE chapters SET transcript = $$For the system design portion, Dana asked Kevin to design a URL shortener that could handle millions of requests a day. He resisted the urge to jump straight to a diagram, even though he'd practiced this exact question and had a design half-memorized already. Instead, he asked clarifying questions first - how many reads versus writes, how important was it that a shortened link never break, was it acceptable for a link to take a few seconds to become active after creation. Dana's answers reshaped the problem more than he expected: reads outnumbered writes by a huge margin, which meant the whole design should optimize for fast lookups over fast writes. Only once he understood the actual constraints did he start sketching the first piece of the architecture, and he narrated his reasoning out loud the entire time, since Dana had made it clear early on that she cared more about how he thought than what he drew.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '4ac8756f-40d0-44d8-baff-a6ab18a25ccf';
UPDATE chapters SET transcript = $$Six months later, when the caching approach changed, Ravi updated the same document instead of letting it quietly go stale like so many others he'd inherited over the years. It took him twenty minutes, tucked into an afternoon that was mostly about something else entirely, and he almost skipped it since nobody had actually asked him to. He'd seen what happened when outdated documentation misled someone confidently in the wrong direction - a new hire had once spent an entire day debugging a problem that a single out-of-date sentence had caused. It was worse than having no documentation at all, since at least an empty page invites a question instead of a wrong answer delivered with total confidence.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '172ef1c5-b085-4ad7-b718-5e12815f95c8';
UPDATE chapters SET transcript = $$When it was his turn, Jamal kept his update just as short as everyone else's had been. "Today I'm working on the payment integration," he said. "I'm adding tests for the new endpoint before I open a pull request." He almost added a longer explanation of a tricky edge case he'd hit that morning, then caught himself - that story belonged in a message to the one teammate who actually needed it, not in front of the whole team.

Nobody asked follow-up questions, not because they didn't care, but because none were needed yet. If something came up during the day, that conversation could happen afterward, in a smaller thread, with only the people who actually needed to be involved, instead of making everyone sit through a problem that concerned two people.

The standup wasn't the place to solve problems. It was the place to make sure everyone knew what everyone else was doing, so problems could be solved quickly later, by the right people, without anyone having to ask around first to figure out who was even touching that part of the system.

By the time the meeting ended, four minutes had passed. Nobody had presented a slide, nobody had opened a shared document, and every person in the room knew exactly what the rest of the team was doing that day.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '03089ac5-dbd3-4dfc-b78a-cb0b8e1c4be6';
UPDATE chapters SET transcript = $$Isabel wrote a unit test for the new discount function before merging it, checking that a ten percent discount produced exactly the value she expected on a handful of realistic inputs, including the edge cases she'd learned to always check - zero, a single item, and an order large enough to trigger a bulk discount at the same time. It took longer to write than the function itself, which used to bother her until a senior engineer pointed out that the test was the part that would still be protecting the codebase two years after everyone forgot how the function worked. It was a small test, but it meant nobody could quietly break that function without something failing loudly first, in a place where the mistake was cheap and obvious instead of showing up as a wrong number on a customer's invoice.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = '348b36f6-145b-4b02-a6c9-17f260f5a246';
UPDATE chapters SET transcript = $$The real cause turned out to be a genuine network call the test made to a third-party service, one that occasionally took just long enough to respond that the test would time out for no reason related to the actual code being tested. Isabel mocked that dependency instead, so the test's result depended only on her own code, not on whether some external API happened to respond in time, or respond at all, or be having a bad day entirely unrelated to anything her team had shipped. The test ran in milliseconds afterward instead of seconds, and more importantly, it stopped failing at random for reasons that had nothing to do with the thing it was actually supposed to verify.$$, audio_url_female = NULL, audio_url_male = NULL WHERE id = 'c527194c-c8e0-4de2-b086-ad1968bd429c';

-- Stray tag cleanup: "the" was accidentally tagged on this chapter during
-- an earlier live click-test of the translate-word feature - not real
-- curated vocabulary, just noise.
DELETE FROM words WHERE chapter_id = '348b36f6-145b-4b02-a6c9-17f260f5a246' AND word = 'the';
